server:
  port: 4110
spring:
  application:
    name: on-the-buses
logging:
  level:
    org:
      springframework:
        cloud:
          consul:
            binder: trace
            discovery: info
