server:
  port: 4110
spring:
  application:
    name: on-the-buses
  cloud:
    function:
      definition: notifyListener
    stream:
      bindings:
        notifyStream-out-0:
          destination: notifications
        notifyListener-in-0:
          destination: notifications
logging:
  level:
    root: debug
#    org:
#      springframework:
#        cloud:
#          consul: trace
#    com:
#      ecwid:
#        consul: trace
