server:
  port: 4110
spring:
  application:
    name: on-the-buses
  cloud:
    stream:
      bindings:
        notifyStream-out-0:
          destination: notifications
        notifyListener-in-0:
          destination: notifications
logging:
  level:
    org:
      springframework:
        cloud:
          consul:
            binder: trace
            discovery: info
#    com:
#      ecwid:
#        consul: trace
