server:
  port: 2110

spring:
  application:
    name: on-the-buses-gw
  cloud:
    consul:
      token: 88fe37aa-6e80-1ab3-a424-b8f6dc93e29a
      enabled: true
      port: 18500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_route
          uri: lb://on-the-buses-svc
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

logging:
  level:
    root: info
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug