server:
  port: 2110

spring:
  application:
    name: on-the-buses-gw
  cloud:
    consul:
      token: 4daf4ec2-03ea-c0b7-e5aa-e2530e9fe75e
      enabled: true
      port: 18500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_route
          uri: lb://on-the-buses-svc
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

logging:
  level:
    root: info
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug